use crate::error::Result;
use std::collections::BTreeSet;
use std::fmt;

/// Structural input layout representing an abstract network matrix.
#[derive(Debug, Clone)]
pub struct Topology {
    pub num_nodes: usize,
    pub edges: Vec<(usize, usize)>,
    pub sinks: BTreeSet<usize>,
}

impl Topology {
    pub fn new(num_nodes: usize) -> Self {
        Self {
            num_nodes,
            edges: Vec::new(),
            sinks: BTreeSet::new(),
        }
    }

    pub fn add_edge(&mut self, source: usize, target: usize) {
        if source < self.num_nodes && target < self.num_nodes {
            self.edges.push((source, target));
        }
    }

    pub fn add_sink(&mut self, node_index: usize) {
        if node_index < self.num_nodes {
            self.sinks.insert(node_index);
        }
    }
}

/// The final resolution payload generated by the mathematical evaluation pipeline.
#[derive(Debug, Clone, PartialEq)]
pub struct PrunerResolution {
    pub action: PolicyAction,
    pub mainland_nodes: Vec<usize>,
    pub island_nodes: Vec<usize>,
    pub connectivity_score: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PolicyAction {
    Allow,
    GarbageCollect,
    FatalBlock,
}

impl fmt::Display for PolicyAction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let val = match self {
            Self::Allow => "ALLOW",
            Self::GarbageCollect => "GARBAGE_COLLECT",
            Self::FatalBlock => "FATAL_BLOCK",
        };
        write!(f, "{}", val)
    }
}

pub struct TauSpectralPruner {
    tau: f64,
    threat_threshold: f64,
    max_iterations: usize,
    tolerance: f64,
    momentum_beta: f64,
    system_start_idx: usize,
}

/// Fluent builder pattern interface to cleanly manage engine instantiation.
pub struct PrunerBuilder {
    tau: f64,
    threat_threshold: f64,
    max_iterations: usize,
    tolerance: f64,
    momentum_beta: f64,
    system_start_idx: usize,
}

impl PrunerBuilder {
    pub fn tau(mut self, value: f64) -> Self {
        self.tau = value;
        self
    }
    pub fn threat_threshold(mut self, value: f64) -> Self {
        self.threat_threshold = value;
        self
    }
    pub fn max_iterations(mut self, value: usize) -> Self {
        self.max_iterations = value;
        self
    }
    pub fn tolerance(mut self, value: f64) -> Self {
        self.tolerance = value;
        self
    }
    pub fn momentum_beta(mut self, value: f64) -> Self {
        self.momentum_beta = value;
        self
    }
    pub fn system_start_idx(mut self, value: usize) -> Self {
        self.system_start_idx = value;
        self
    }

    pub fn build(self) -> TauSpectralPruner {
        TauSpectralPruner {
            tau: self.tau,
            threat_threshold: self.threat_threshold,
            max_iterations: self.max_iterations,
            tolerance: self.tolerance,
            momentum_beta: self.momentum_beta,
            system_start_idx: self.system_start_idx,
        }
    }
}

impl TauSpectralPruner {
    pub fn builder() -> PrunerBuilder {
        PrunerBuilder {
            tau: 0.0,
            threat_threshold: 2.0,
            max_iterations: 10_000,
            tolerance: 1e-9,
            momentum_beta: 0.5,
            system_start_idx: 5,
        }
    }

    /// Computes a polynomial-time spectral bisection heuristic approximation of the network topology 
    /// via the Fiedler vector to determine containment policy.
    #[allow(clippy::needless_range_loop)]
    pub fn prune(
        &self,
        topology: &Topology,
        system_boundary_len: usize,
    ) -> Result<PrunerResolution> {
        let n = topology.num_nodes;

        if n < 3 {
            return Ok(PrunerResolution {
                action: PolicyAction::Allow,
                mainland_nodes: (0..n).filter(|i| !topology.sinks.contains(i)).collect(),
                island_nodes: Vec::new(),
                connectivity_score: 0.0,
            });
        }

        // 1. Structural Adjacency and Degree mapping
        let mut adj = vec![Vec::new(); n];
        let mut degrees = vec![0.0; n];

        for &(u, v) in &topology.edges {
            if !topology.sinks.contains(&u) && !topology.sinks.contains(&v) && u != v {
                adj[u].push(v);
                adj[v].push(u);
                degrees[u] += 1.0;
                degrees[v] += 1.0;
            }
        }

        let max_degree = degrees.iter().copied().fold(0.0, f64::max);
        if max_degree == 0.0 {
            return Ok(PrunerResolution {
                action: PolicyAction::Allow,
                mainland_nodes: (0..n).filter(|i| !topology.sinks.contains(i)).collect(),
                island_nodes: Vec::new(),
                connectivity_score: 0.0,
            });
        }

        // 2. Heavy-Ball Momentum Shifted Laplacian Power Iteration
        // Note: Memory allocation of scratch vectors is O(N) at the function call boundary,
        // but their buffers are mutated entirely in-place to achieve zero allocations inside the iterative loop.
        let alpha = 1.0 / (2.0 * max_degree + 1.1);
        let mut v_vec = vec![0.0; n];

        // Break spatial symmetry using high-frequency continuous perturbation.
        // Apply Zero-Degree Clamping Regularization: completely disconnected nodes (degree == 0)
        // are clamped to a static positive value (1.0) to predictably guide them into the
        // primary Mainland partition, preventing chaotic noise-driven edge breaks.
        for i in 0..n {
            if !topology.sinks.contains(&i) {
                if degrees[i] == 0.0 {
                    v_vec[i] = 1.0; // Zero-Degree Clamping Regularization
                } else {
                    v_vec[i] = (i as f64).sin();
                }
            }
        }

        let init_norm: f64 = v_vec.iter().map(|x| x * x).sum::<f64>().sqrt();
        if init_norm > 1e-15 {
            for x in &mut v_vec {
                *x /= init_norm;
            }
        }

        let mut v_prev_m = v_vec.clone();
        let mut v_m = vec![0.0; n];
        let mut v_next = vec![0.0; n];
        let mut fiedler_value = 0.0;

        for _ in 0..self.max_iterations {
            // Null-space projection: force zero steady-state matrix mean
            let mut sum = 0.0;
            let mut count = 0.0;
            for i in 0..n {
                if !topology.sinks.contains(&i) {
                    sum += v_vec[i];
                    count += 1.0;
                }
            }
            let mean = if count > 0.0 { sum / count } else { 0.0 };
            for i in 0..n {
                if !topology.sinks.contains(&i) {
                    v_vec[i] -= mean;
                }
            }

            // Power Step evaluation: M = I - alpha * L
            for i in 0..n {
                if topology.sinks.contains(&i) {
                    v_m[i] = 0.0;
                    continue;
                }
                v_m[i] = (1.0 - alpha * degrees[i]) * v_vec[i];
                for &neighbor in &adj[i] {
                    v_m[i] += alpha * v_vec[neighbor];
                }
            }

            // Heavy Ball Acceleration Injection
            for i in 0..n {
                v_next[i] = v_m[i] + self.momentum_beta * (v_m[i] - v_prev_m[i]);
            }

            let norm_sq: f64 = v_next.iter().map(|x| x * x).sum();
            let norm = norm_sq.sqrt();
            if norm < 1e-15 {
                break;
            }

            let mut max_diff = 0.0;
            for i in 0..n {
                if !topology.sinks.contains(&i) {
                    v_next[i] /= norm;
                    max_diff = f64::max(max_diff, (v_next[i] - v_vec[i]).abs());
                } else {
                    v_next[i] = 0.0;
                }
            }

            // Continuous Rayleigh Quotient calculation for checking convergence tracking
            let mut v_l_v = 0.0;
            for i in 0..n {
                if topology.sinks.contains(&i) {
                    continue;
                }
                let mut row_sum = degrees[i] * v_next[i];
                for &neighbor in &adj[i] {
                    row_sum -= v_next[neighbor];
                }
                v_l_v += v_next[i] * row_sum;
            }
            fiedler_value = v_l_v;

            // In-place copy to avoid vector recreation and heap allocation thrashing
            v_prev_m.copy_from_slice(&v_m);
            v_vec.copy_from_slice(&v_next);

            if max_diff < self.tolerance {
                break;
            }
        }

        // 3. Absolute Injected Tau Bisection Classification
        let mut side_small = Vec::new();
        let mut side_large = Vec::new();

        for i in 0..n {
            if topology.sinks.contains(&i) {
                continue;
            }
            if v_vec[i] <= self.tau {
                side_small.push(i);
            } else {
                side_large.push(i);
            }
        }

        // Enforce deterministic partition volume classification
        let (mainland, island) = if side_small.len() > side_large.len() {
            (side_small, side_large)
        } else {
            (side_large, side_small)
        };

        let island_set: BTreeSet<usize> = island.iter().copied().collect();

        // 4. Advanced Semantic Threat Metric Analysis Pipeline
        let mut to_system = 0.0;
        let mut internal = 0.0;

        for &(u, v) in &topology.edges {
            let u_in_island = island_set.contains(&u);
            let v_in_island = island_set.contains(&v);
            let u_is_system = u >= self.system_start_idx && u <= system_boundary_len;
            let v_is_system = v >= self.system_start_idx && v <= system_boundary_len;

            if u_in_island {
                if v_is_system {
                    to_system += 1.0;
                } else if v_in_island && !u_is_system {
                    internal += 1.0;
                }
            }
            if v_in_island && u != v {
                if u_is_system {
                    to_system += 1.0;
                } else if u_in_island && !v_is_system {
                    internal += 1.0;
                }
            }
        }

        let island_local_nodes: Vec<usize> = island
            .iter()
            .copied()
            .filter(|&i| !(i >= self.system_start_idx && i <= system_boundary_len))
            .collect();
        let island_len = island_local_nodes.len() as f64;
        let system_len = system_boundary_len as f64;

        // Metric 1: Scale-Invariant Cluster Density Ratio
        // Normalizes internal cluster edges against both the island size and system boundary
        // size to maintain identical detection sensitivity across widely varying network scales.
        let normalized_ratio = if to_system > 0.0 && island_len > 0.0 {
            (internal * system_len) / (to_system * island_len)
        } else if !island_local_nodes.is_empty() {
            f64::INFINITY
        } else {
            0.0
        };

        // Metric 2: Instruction neglect checking
        let instruction_neglect = if !island_local_nodes.is_empty() {
            to_system / island_len
        } else {
            1.0
        };

        // Metric 3: Micro-Steering Single-Token Tripwire
        // An instantaneous security quarantine override engineered specifically for highly
        // optimized, microscopic single-node steering or adversarial vector injection attacks.
        let is_control_vector =
            island_len == 1.0 && internal == 0.0 && to_system > 0.0 && to_system < 2.0;

        // 5. Policy Enforcement Decision Processing
        if cfg!(debug_assertions) {
            println!(
                "DEBUG: island={:?}, mainland={:?}, fiedler={:?}",
                island, mainland, v_vec
            );
            println!("DEBUG: to_system={}, internal={}, normalized_ratio={}, instruction_neglect={}, is_control_vector={}", to_system, internal, normalized_ratio, instruction_neglect, is_control_vector);
        }
        let action = if island_local_nodes.is_empty() || system_boundary_len == 0 {
            PolicyAction::Allow
        } else if normalized_ratio > self.threat_threshold
            || instruction_neglect < 0.1
            || is_control_vector
        {
            PolicyAction::FatalBlock
        } else {
            PolicyAction::GarbageCollect
        };
        if cfg!(debug_assertions) {
            println!("DEBUG: action={:?}", action);
        }

        // Exclude system boundary nodes from the final returned vectors,
        // but keep them in the classification internally for correct threat metrics.
        let final_mainland: Vec<usize> = mainland
            .into_iter()
            .filter(|&i| !(i >= self.system_start_idx && i <= system_boundary_len))
            .collect();
        let final_island: Vec<usize> = island
            .into_iter()
            .filter(|&i| !(i >= self.system_start_idx && i <= system_boundary_len))
            .collect();

        Ok(PrunerResolution {
            action,
            mainland_nodes: final_mainland,
            island_nodes: final_island,
            connectivity_score: fiedler_value,
        })
    }
}
